version: '3'
services:
  webserver:
    container_name: cont_web
    build: ./docker/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/docker/www:/var/www/html
    networks:
      - net1
    links:
      - db

  db:
    image: mysql:5.7
    container_name: cont_db
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=db_runwaytest
    networks:
      - net1

networks:
   net1:
     external: true
